server:
  port: 9001

spring:
  application:
    name: EKYC_DEV
  datasource:
    url: jdbc:h2:mem:dbeykc;DATABASE_TO_UPPER=false
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/h2
    validate-migration-naming: true

external:
  gatewaypayee:
    name: gateway-payee-consumer
    url: http://localhost:9001/payee-gateway/
  historypayee:
    name: gateway-payee-consumer
    url: http://localhost:9002/payee-history/

